library(shiny)
library(shinythemes)

ui <- fluidPage(theme = shinytheme("darkly"),
  navbarPage(
    h4("ZOMBIE WORLD"),
    tabPanel(h4("Movies & Series List")),
    sidebarLayout(position = "right",
      sidebarPanel(
        p(h3(strong(em(span("IMDB", style = "color:yellow"),"&",span("Rotten Tomatoes", style = "color:red"),"Ratings")))),
        br(),
        p(h4(strong(em("WHAT IS THE PURPOSE OF THE RATING SYSTEM?", style = "font-size:20px")))),
        p(h3("Movie ratings provide parents with advance information about the content of movies to help them determine what movies are appropriate for their children at any age. Ratings are assigned by a board of parents who consider factors such as violence, sex, language and drug use, then assign a rating they believe the majority of American parents would give a movie.", style = "font-size:20px")),
        br(),
        img(src = "imdb.svg", height = 100),
        br(),
        p(h3("IMDb registered users can cast a vote (from 1 to 10) on every released title in the database. Individual votes are then aggregated and summarized as a single IMDb rating, visible on the title's main page.", style = "font-size:20px")),
        br(),
        img(src = "rottentomatoes.jpg", height = 150),
        br(),
        p(h3("Rotten Tomatoes and the Tomatometer score are the world's most trusted recommendation resources for quality entertainment. As the leading online aggregator of movie and TV show reviews from critics, we provide fans with a comprehensive guide to what's Fresh - and what's Rotten - in theaters and at home.", style = "font-size:20px")),
        br(),
        br(),
        br(),
        br(),
        p(h3(em(span("Click on the below Movie & Series 'Titles' to watch:", style = "color:orange")))),
        br(),
        br(),
        p(h3(em(a ("BETAAL:", href = ("https://www.netflix.com/in/title/81061789"))))),
        br(),
        p(h3(em(" IMDB Rating: 5.3 / 10 "))),
        p(h3(em(" 78% Google users liked this TV Show "))),
        br(),
        br(),
        br(),
        p(h3(em(a ("BLACK SUMMER:", href = ("https://www.netflix.com/in/title/80198988"))))),
        br(),
        p(h3(em(" IMDB Rating: 6.4 / 10 "))),
        p(h3(em(" ROTTEN TOMATOES Rating: 78% "))),
        p(h3(em("79% Google users liked this TV Show "))),
        br(),
        br(),
        br(),
        p(h3(em(a ("ALIVE:", href = ("https://www.netflix.com/in/title/81240831"))))),
        br(),
        p(h3(em(" IMDB Rating: 6.2 / 10 "))),
        p(h3(em(" ROTTEN TOMATOES Rating: 86% "))),
        br(),
        br(),
        br(),
        p(h3(em(a ("KINGDOM:", href = ("https://www.netflix.com/in/title/80180171"))))),
        br(),
        p(h3(em(" IMDB Rating: 8.4 / 10 "))),
        p(h3(em("ROTTEN TOMATOES Rating: 96% "))),
        p(h3(em("95% Google users liked this TV Show "))),
        br(),
        br(),
        br(),
        p(h3(em(a ("THE WALKING DEAD:", href = ("https://www.netflix.com/in/title/70177057"))))),
        br(),
        p(h3(em(" IMDB Rating: 8.2 / 10 "))),
        p(h3(em("ROTTEN TOMATOES Rating: 81% "))),
        p(h3(em("94% liked this TV Show "))),
        br(),
        br(),
        br(),
        helpText(h3(span(em("Rate your favourite Movie or Show!", style = "color:yellow")))),
        
        selectInput("var",
                    label = h3("Choose your favourite Movie or Series:"),
                    choices = list("Betaal", 
                                   "Black Summer",
                                   "Alive", 
                                   "Kingdom",
                                   "The walking dead"),
                    selected = "The walking dead"),
        
        sliderInput("range", 
                    label = h3("Rate your selected choice out of 10 :"),
                    min = 0, max = 10, value = 9),
        submitButton("Submit"),
        br(),
        textOutput("selected_var"),
        textOutput("rate_number")
        
      ),
      
    mainPanel(
              h1(strong("Best Zombie Shows & Movies On", span("Netflix", style = "color:red")), align = "center"),
              br(),
              br(),
              
              p(h3("Not all shows about the undead are created equal, but these Netflix Zombies are some of the best that TV has to offer.")),
              br(),
              p(h4(strong("BY",span("MANSOOR KHAN LODI", style = "color:orange")))),
              p(h4("OCTOBER 10,2020")),
              br(),
              br(),
              img(src = "zombiegif1.gif", height = 400, width = 800, align = "center"),
              br(),
              br(),
              p(h3("If you've already seen every zombie movie Netflix has to offer, why not find a nice zombie-related TV series to binge watch, as well? Bear in mind, not all shows about the undead are created equal. Although there are plenty of scary, flesh-tearing zombies in shows like The Walking Dead, many shows within the genre offer a cocktail of horror, comedy, historical drama, and crime investigation.")),
              p(h3("In other words, there's a zombie show for everyone whether you want to laugh, cry, or hide beneath the covers. Here are 10 of the best zombie TV shows on Netflix.")),
              br(),
              br(),
              h2(strong(span("5.", style = "color:orange"))),
              p(h2(strong(span("BETAAL", style = "color:orange")))),
              img(src = "betaal2.jpg", height = 538, width = 956),
              br(),
              br(),
              helpText(h4("2020 | 16+ | 1 Season | Horror TV Serials")),
              br(),
              p(h3(em(span("Starring:", style = "color:red"),"Viineet Kumar,Aahana Kumra,Suchitra Pillai"))),
              p(h3(em(span("Creators:", style = "color:red"),"Patrick Graham"))),
              p(h3("While on a mission to displace the natives of Campa forest in order to build a highway, Sirohi and his squad unwittingly unleash the curse of Betaal mountain. A remote village quickly becomes the arena of a breathless battle when a two-century-old East India Company Colonel, infected with Betaal's curse, and his battalion of blood-thirsty zombie redcoats are released from their tomb, attacking anything with a pulse. The CIPD forces are pitted against the undead army that wreaks havoc on the people and threatens to end civilisation as we know it.")),
              br(),
              p(h3("Watch the",em(span("Betaal", style = "color:red"),"trailer here:"))),
              br(),
              HTML('<iframe width="956" height="538" src="https://www.youtube.com/embed/YSEVaVc-nOo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'),
              br(),
              br(),
              h2(strong(span("4.", style = "color:orange"))),
              p(h2(strong(span("BLACK SUMMMER", style = "color:orange")))),
              img(src = "blacksummer.png", height = 538, width = 956),
              br(),
              br(),
              helpText(h4("2019 | 18+ | 1 Season | US TV Shows")),
              br(),
              p(h3(em(span("Starring:", style = "color:red"),"Jaime King,Justin Chu Cary,Christine Lee"))),
              p(h3(em(span("Creators:", style = "color:red"),"Karl Schaefer,John Hyams"))),
              p(h3("Set in the 'Z Nation' universe, this series follows a crack team of special forces as it fights for hope in the darkest hours of the zombie apocalypse.")),
              br(),
              p(h3("Watch the",em(span("Black Summer", style = "color:red"),"trailer here:"))),
              br(),
              HTML('<iframe width="956" height="538" src="https://www.youtube.com/embed/tQA1omPJN24" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'),
              br(),
              br(),
              h2(strong(span("3.", style = "color:orange"))),
              p(h2(strong(span("Alive", style = "color:orange")))),
              img(src = "alive.jpg", height = 538, width = 956),
              br(),
              br(),
              helpText(h4("2020 | 16+ | 1h 38m | Thriller Movies")),
              br(),
              p(h3(em(span("Starring:", style = "color:red"),"Yoo Ah-in,Park Shin-hye"))),
              p(h3("As a grisly virus rampages a city, a lone man stays locked inside his apartment, digitally cut off from seeking help and desperate to find a way out.")),
              br(),
              p(h3("Watch the",em(span("Alive", style = "color:red"),"trailer here:"))),
              br(),
              HTML('<iframe width="956" height="538" src="https://www.youtube.com/embed/jQ8CCg1tOqc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'),
              br(),
              br(),
              h2(strong(span("2.", style = "color:orange"))),
              p(h2(strong(span("Kingdom", style = "color:orange")))),
              img(src = "kingdom2.jpg", height = 538, width = 956),
              br(),
              br(),
              helpText(h4("2019 | 18+ | 2 Seasons | Period Pieces")),
              br(),
              p(h3(em(span("Starring:", style = "color:red"),"Ju Ji-hoon,Ryu Seung-ryong,Bae Doona"))),
              p(h3(em(span("Creators:", style = "color:red"),"Kim Eun-hee,Kim Seong-hun,Park Inje"))),
              p(h3("While strange rumors about their ill king grip a kingdom, the crown prince becomes their only hope against a mysterious plague overtaking the land.")),
              br(),
              p(h3("Watch the",em(span("Kingdom", style = "color:red"),"trailer here:"))),
              br(),
              HTML('<iframe width="956" height="538" src="https://www.youtube.com/embed/4l-yByZpaaM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'),
              br(),
              br(),
              h2(strong(span("1.", style = "color:orange"))),
              p(h2(strong(span("The Walking Dead", style = "color:orange")))),
              img(src = "walkingdead1.jpg", height = 538, width = 956),
              br(),
              br(),
              helpText(h4("2010 | 18+ | 9 Seasons | US TV Shows")),
              br(),
              p(h3(em(span("Starring:", style = "color:red"),"Andrew Lincoln,Steven Yeun,Norman Reedus"))),
              p(h3(em(span("Creators:", style = "color:red"),"Frank Darabont, Angela Kang"))),
              p(h3("In the wake of a zombie apocalypse, survivors hold on to the hope of humanity by banding together to wage a fight for their own survival.")),
              br(),
              p(h3("Watch the",em(span("The walking Dead", style = "color:red"),"trailer here:"))),
              br(),
              HTML('<iframe width="956" height="538" src="https://www.youtube.com/embed/gobV63BPDMY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'),
              br(),
              br(),
              br(),
              p(strong(h3(em(span("Keep in touch for more updates!", style = "color:orange")))), align = 'center')
              
          ),        
       )
    ),
  )


server <- function(input, output) {
  output$selected_var <- renderText({
    paste("You have selected '", input$var, "'")
  })
  
  output$rate_number <- renderText({
    paste("Thank you for selecting your favourite show and rating it", input$range,"!")
  })
}

shinyApp(ui = ui, server = server )